// <auto-generated />
using System;
using BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211021003830_inicio1")]
    partial class inicio1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorServer.Data.Arquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caminho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Arquivo");
                });

            modelBuilder.Entity("BlazorServer.Data.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCargo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496869c3-4f5f-4bc2-9c9a-ae8b34d2fabc"),
                            NomeCargo = "Tutor"
                        },
                        new
                        {
                            Id = new Guid("eba2cf54-ecfc-4f7d-a81d-811ce6e68830"),
                            NomeCargo = "Secretaria"
                        },
                        new
                        {
                            Id = new Guid("32fd915b-063f-4e8f-b239-3ce50b9230e3"),
                            NomeCargo = "Comercial"
                        },
                        new
                        {
                            Id = new Guid("1677b133-384e-401f-9630-ec7d9fc60a59"),
                            NomeCargo = "Coordenador"
                        },
                        new
                        {
                            Id = new Guid("9f8f33d1-94c9-49c9-a35f-440bce9a87c5"),
                            NomeCargo = "Professor"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodPonto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Contratacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Demissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HoraAula")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UnidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Colaboradors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d69a83fc-b88d-4e38-a2d1-13499c9ea7b1"),
                            Ativo = false,
                            CodPonto = 39,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 385, DateTimeKind.Local).AddTicks(151),
                            HoraAula = 52.00m,
                            Nome = "ALEXSANDRA KETHY DE FRANÇA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("494b34a7-25e0-4254-9525-ba07a54367d7"),
                            Ativo = false,
                            CodPonto = 22,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8153),
                            HoraAula = 52.00m,
                            Nome = "ALVARO RICK P. VIEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("64e6655f-6cbb-4041-b802-c3a3789f2ec3"),
                            Ativo = false,
                            CodPonto = 50,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8280),
                            HoraAula = 52.00m,
                            Nome = "AMADEU JUNIOR FERREIRA DE LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("26f02b31-deea-4300-9896-5337a2044dee"),
                            Ativo = false,
                            CodPonto = 46,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8287),
                            HoraAula = 52.00m,
                            Nome = "ANA ALICE DA MOTA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b262b620-a3d8-442b-b3ee-81d44a519a26"),
                            Ativo = false,
                            CodPonto = 35,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8293),
                            HoraAula = 52.00m,
                            Nome = "ANDERSON CRISTIANO SALES SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("911825ef-4473-4055-b0f6-407ccd7ea77b"),
                            Ativo = false,
                            CodPonto = 5,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8299),
                            HoraAula = 52.00m,
                            Nome = "ANDRÉ DA CONCEIÇÃO SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c6828a4c-dd91-47dd-9be2-faa0ba4317ad"),
                            Ativo = false,
                            CodPonto = 37,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8305),
                            HoraAula = 52.00m,
                            Nome = "ANDREA REGINA J. B. RODRIGUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("84335af1-3b57-4dea-af1d-f7dcb6b275e9"),
                            Ativo = false,
                            CodPonto = 42,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8310),
                            HoraAula = 52.00m,
                            Nome = "ANTONIA IVANA COSTA SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("95513b5a-3366-4fa6-a9db-81e2c5c19c55"),
                            Ativo = false,
                            CodPonto = 26,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8330),
                            HoraAula = 52.00m,
                            Nome = "CACIELY VALERIO GOMES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("610c832b-1bdc-43d0-8d85-b9a9b132605e"),
                            Ativo = false,
                            CodPonto = 25,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8335),
                            HoraAula = 52.00m,
                            Nome = "CLEUDILENE DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2c84cfce-cc97-4863-81b6-5f3a154de80e"),
                            Ativo = false,
                            CodPonto = 44,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8340),
                            HoraAula = 52.00m,
                            Nome = "CRISTIANE SOARES COSTA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("16f37c72-746b-49d2-b15c-4d7363e2b2fb"),
                            Ativo = false,
                            CodPonto = 40,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8345),
                            HoraAula = 52.00m,
                            Nome = "DANIEL DE ARAUJO MOTA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a1c40dad-73f5-44ca-bc49-1b18d0724db9"),
                            Ativo = false,
                            CodPonto = 41,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8351),
                            HoraAula = 52.00m,
                            Nome = "DAYARA BORGES LUCENA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("33d30ac6-d264-4916-8dbb-bc25a1ea626d"),
                            Ativo = false,
                            CodPonto = 36,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8356),
                            HoraAula = 52.00m,
                            Nome = "DENILZA  ALVES PINTO DUARTE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("0430df7c-b52c-4398-bc00-ac651d014094"),
                            Ativo = false,
                            CodPonto = 28,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8361),
                            HoraAula = 52.00m,
                            Nome = "DEREK DILERVANDO DE O. PANTOJA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("abf66ca5-41c7-487e-ad91-8e82e1abebe3"),
                            Ativo = false,
                            CodPonto = 19,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8367),
                            HoraAula = 52.00m,
                            Nome = "DHONAYARA DA SILVA DE CAMPOS AMORIM",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c4e1d5f6-3863-4e64-b295-b33d27587fe1"),
                            Ativo = false,
                            CodPonto = 2,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8375),
                            HoraAula = 52.00m,
                            Nome = "EDI",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("11c0b584-b024-4819-a199-a1bd126b7d54"),
                            Ativo = false,
                            CodPonto = 45,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8381),
                            HoraAula = 52.00m,
                            Nome = "ELAINE DE JESUS REZENDE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("dcde7e29-842e-4da6-aaa2-ce4e600c0b48"),
                            Ativo = false,
                            CodPonto = 48,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8386),
                            HoraAula = 52.00m,
                            Nome = "ERCILIO DE CASTRO  BARBOZA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f6b16a1a-02b9-4841-92a8-bef949f55c2d"),
                            Ativo = false,
                            CodPonto = 29,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8390),
                            HoraAula = 52.00m,
                            Nome = "FERNANDO CABRAL DA FONSECA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ec4ae8b1-c134-4240-b919-c8b31ecfbcba"),
                            Ativo = false,
                            CodPonto = 24,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8395),
                            HoraAula = 52.00m,
                            Nome = "FRANCINOLIA R A L C",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("20c6b6e0-f06b-4590-964a-37c7e1df10c5"),
                            Ativo = false,
                            CodPonto = 9,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8400),
                            HoraAula = 52.00m,
                            Nome = "GLICIANE ESTEPHANE JACOME DE SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6abc60e0-7bdb-4917-854c-c8b639afeae6"),
                            Ativo = false,
                            CodPonto = 31,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8406),
                            HoraAula = 52.00m,
                            Nome = "HUDLER LEITE DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3099706e-64f4-4ed6-bf11-1aedba2b3e2a"),
                            Ativo = false,
                            CodPonto = 33,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8411),
                            HoraAula = 52.00m,
                            Nome = "IRISMAR SILVA CIRINO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("886c92b0-cc3b-4a45-b5e8-089e15723f80"),
                            Ativo = false,
                            CodPonto = 34,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8419),
                            HoraAula = 52.00m,
                            Nome = "JAKELLYNE ALVES BRANDÃO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b193f695-d90b-4b67-9234-0cd695337633"),
                            Ativo = false,
                            CodPonto = 10,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8425),
                            HoraAula = 52.00m,
                            Nome = "JHYEIVSON WALLINTER SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a1ee3dcd-4832-4bd7-a8bd-38caf4095852"),
                            Ativo = false,
                            CodPonto = 43,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8430),
                            HoraAula = 52.00m,
                            Nome = "JORDANIA DE MACEDO MENDONÇA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("cb36a9ba-98f0-4991-bb95-eb56f4484a95"),
                            Ativo = false,
                            CodPonto = 11,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8435),
                            HoraAula = 52.00m,
                            Nome = "JORGE CLESIO SILVA E SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4b6e7d3e-faee-4cc6-aff4-d8c871b406f0"),
                            Ativo = false,
                            CodPonto = 12,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8440),
                            HoraAula = 52.00m,
                            Nome = "JORGE FERNANDO CASTRO SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("298b1cf0-dceb-4978-9a64-a02f2249f7e9"),
                            Ativo = false,
                            CodPonto = 51,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8444),
                            HoraAula = 52.00m,
                            Nome = "JUCIENE IONARIA DE S. GABRIEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3384d4c4-3144-46eb-bb5a-7d7d32079fb4"),
                            Ativo = false,
                            CodPonto = 55,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8448),
                            HoraAula = 52.00m,
                            Nome = "LEILSON RODRIGUES DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("65690e1a-249c-494f-a7b6-d28f7e85b3ac"),
                            Ativo = false,
                            CodPonto = 13,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8514),
                            HoraAula = 52.00m,
                            Nome = "LORENA MATOS SILVA PRADO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("983687fa-324d-4740-be1a-e1c667ff5d2e"),
                            Ativo = false,
                            CodPonto = 30,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8522),
                            HoraAula = 52.00m,
                            Nome = "LUANA MARTINS ROCHA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("efbae2ec-df98-417d-ac51-ae617fc7575f"),
                            Ativo = false,
                            CodPonto = 53,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8527),
                            HoraAula = 52.00m,
                            Nome = "MARIANA LEAL OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("56d170b1-6b09-49ec-b569-e1d7c544ea53"),
                            Ativo = false,
                            CodPonto = 14,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8532),
                            HoraAula = 52.00m,
                            Nome = "MAYARA DE OLIVEIRA PEREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c7cc16be-5278-4f84-a945-d274582837f2"),
                            Ativo = false,
                            CodPonto = 27,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8537),
                            HoraAula = 52.00m,
                            Nome = "MONICA HELLE DE LIMA ROSA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("478ede76-5a84-4225-841f-74ade11233b2"),
                            Ativo = false,
                            CodPonto = 3,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8542),
                            HoraAula = 52.00m,
                            Nome = "NATANAEL SOUA BARROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6a2413b3-5f00-4aa0-bff5-9a303251f4c0"),
                            Ativo = false,
                            CodPonto = 54,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8547),
                            HoraAula = 52.00m,
                            Nome = "NATHALIA DA SILVA MARQUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1cef62f4-6205-49a4-b76e-719fe9e404b2"),
                            Ativo = false,
                            CodPonto = 38,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8553),
                            HoraAula = 52.00m,
                            Nome = "NILCELIA DE LIMA ROCHA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("cf0f0f3d-5511-4ba4-8630-9ed8cd88c339"),
                            Ativo = false,
                            CodPonto = 23,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8558),
                            HoraAula = 52.00m,
                            Nome = "RAIANE OCAES OLIVEIRA DE SOUZA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("14ffbca7-d2a0-4acc-a23e-cf29f33d52c9"),
                            Ativo = false,
                            CodPonto = 20,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8566),
                            HoraAula = 52.00m,
                            Nome = "RAILENE CONCEIÇÃO DE CARVALHO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("563e99b3-ce69-496c-9e63-9c27ff11348f"),
                            Ativo = false,
                            CodPonto = 15,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8571),
                            HoraAula = 52.00m,
                            Nome = "RAQUEL BRITO DOS SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8fad249b-d6b0-4d38-aa2b-179fc8d28eb6"),
                            Ativo = false,
                            CodPonto = 32,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8577),
                            HoraAula = 52.00m,
                            Nome = "ROSILENE CONCEIÇÃO DE CARVALHO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("28263b1d-332d-4ddf-ad2d-57a174775d39"),
                            Ativo = false,
                            CodPonto = 16,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8582),
                            HoraAula = 52.00m,
                            Nome = "SAMARA DE OLIVEIRA MOREIRA CABRAL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7a3deba9-9e4f-4b42-a0fd-07c0561ec8cf"),
                            Ativo = false,
                            CodPonto = 47,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8587),
                            HoraAula = 52.00m,
                            Nome = "SILVIO VIANA DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("36db8abb-e12d-46ed-97ce-9a27738926b6"),
                            Ativo = false,
                            CodPonto = 4,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8591),
                            HoraAula = 52.00m,
                            Nome = "SIRLEI VANDA ANDRADE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6086736c-d497-4c64-a358-85ca6c5992c2"),
                            Ativo = false,
                            CodPonto = 56,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8596),
                            HoraAula = 52.00m,
                            Nome = "SUANY ISAIAS DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f557edb4-2255-404d-9dea-ecfba17762a5"),
                            Ativo = false,
                            CodPonto = 17,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8601),
                            HoraAula = 52.00m,
                            Nome = "TOMAZ B. NERY S. CAMPOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("855229da-8062-4bc5-a80a-6a2b9718ebd3"),
                            Ativo = false,
                            CodPonto = 49,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8608),
                            HoraAula = 52.00m,
                            Nome = "VANESSA MOURA DE ALMEIDA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("867785db-f060-4f30-afd7-8e546feb614e"),
                            Ativo = false,
                            CodPonto = 18,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8613),
                            HoraAula = 52.00m,
                            Nome = "WALDEMIR DE SOUZA REIS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3fa4bde4-5489-4ed7-84ad-690d0c078a7d"),
                            Ativo = false,
                            CodPonto = 21,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8618),
                            HoraAula = 52.00m,
                            Nome = "WALISON RICARDO GOES DA PASCOA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2681b1ad-5e76-4664-aae9-04575ff21ac8"),
                            Ativo = false,
                            CodPonto = 52,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8623),
                            HoraAula = 52.00m,
                            Nome = "WARLY BEZERRA DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7b035088-f42c-4469-8cce-a796a4f8f130"),
                            Ativo = false,
                            CodPonto = 57,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8627),
                            HoraAula = 52.00m,
                            Nome = "RENATA CAMILY SIRQUEIRA PALHETA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("45473d9d-7a27-4a56-9f64-edb7f890ad1a"),
                            Ativo = false,
                            CodPonto = 58,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8631),
                            HoraAula = 52.00m,
                            Nome = "YURI DO CARMO MOREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("fd6087d4-f2f9-4a7f-9db5-3f52c9786081"),
                            Ativo = false,
                            CodPonto = 59,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8635),
                            HoraAula = 52.00m,
                            Nome = "VALDEMAR JUSTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("13eb0df2-0900-4081-b77b-a85e418917e1"),
                            Ativo = false,
                            CodPonto = 60,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8640),
                            HoraAula = 52.00m,
                            Nome = "EDSON DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("243f10c6-37a7-4791-8519-9f7007b4844e"),
                            Ativo = false,
                            CodPonto = 61,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8647),
                            HoraAula = 52.00m,
                            Nome = "BRUNO MORAES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("bf928419-4a88-4f8a-b782-6c0fff65e263"),
                            Ativo = false,
                            CodPonto = 6,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8653),
                            HoraAula = 52.00m,
                            Nome = "CIBELLE DA SILVA CARVALHO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8614a2ff-71fb-480e-8f6e-1100d84dbb55"),
                            Ativo = false,
                            CodPonto = 62,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8657),
                            HoraAula = 52.00m,
                            Nome = "THALYTA RODRIGUES BARBOSA GIL		 ",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2f32ba63-8243-47c5-89bf-08a804e07732"),
                            Ativo = false,
                            CodPonto = 64,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8662),
                            HoraAula = 52.00m,
                            Nome = "DHELEN SILVA ALMEIDA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("271a8f6b-291f-48cb-90a1-9a8d530c5144"),
                            Ativo = false,
                            CodPonto = 63,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8666),
                            HoraAula = 52.00m,
                            Nome = "DEUZIMAR LIMA DOS SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("58415de7-4fcc-4277-b29e-eb2cba823533"),
                            Ativo = false,
                            CodPonto = 7,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8671),
                            HoraAula = 52.00m,
                            Nome = "DAYARA NOLETO ALVES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c645463d-86e6-431f-9b65-850affb7c88c"),
                            Ativo = false,
                            CodPonto = 65,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8675),
                            HoraAula = 52.00m,
                            Nome = "LORENE SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3a8914af-ce35-4ba7-99fb-42fe821b277a"),
                            Ativo = false,
                            CodPonto = 66,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8680),
                            HoraAula = 52.00m,
                            Nome = "JOSE ROBERTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("06841848-09b8-41f8-b341-80fc20bb881a"),
                            Ativo = false,
                            CodPonto = 67,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8687),
                            HoraAula = 52.00m,
                            Nome = "GABRIEL DE ARAUJO VEIGA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("dbf8ffe1-44cb-4c60-a152-975a10a830d7"),
                            Ativo = false,
                            CodPonto = 68,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8692),
                            HoraAula = 52.00m,
                            Nome = "MIREIA SOZA BARROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("53835cab-4bfd-45e8-9444-28ba7c923a62"),
                            Ativo = false,
                            CodPonto = 69,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8697),
                            HoraAula = 52.00m,
                            Nome = "MARINA LINS DE SOUZA AMADO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("09385b3e-448c-42f0-b2dc-f381c4ee31bb"),
                            Ativo = false,
                            CodPonto = 70,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8701),
                            HoraAula = 52.00m,
                            Nome = "ALVESLENE LEMS C DAMACENO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("491dc553-3695-4037-9ab2-90572d6ac0a8"),
                            Ativo = false,
                            CodPonto = 71,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8705),
                            HoraAula = 52.00m,
                            Nome = "APINAGES PIRES CARDOSO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f1238f6a-21f1-457f-812c-8beee7c29110"),
                            Ativo = false,
                            CodPonto = 72,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8710),
                            HoraAula = 52.00m,
                            Nome = "LUCAS MEDEIROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f206e275-c629-4719-9f9f-fcada7bb9c42"),
                            Ativo = false,
                            CodPonto = 73,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8714),
                            HoraAula = 52.00m,
                            Nome = "ELIANE MORAES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8693cd38-c7af-41b0-b4e0-fccfd181e42f"),
                            Ativo = false,
                            CodPonto = 74,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8751),
                            HoraAula = 52.00m,
                            Nome = "DANIELLE LIMA SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("85c07e39-f035-44d1-bd5d-06d4f99aac35"),
                            Ativo = false,
                            CodPonto = 75,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8759),
                            HoraAula = 52.00m,
                            Nome = "TASSIO VINICIUS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("af973e9e-8072-4cd5-bff0-782df3c1b656"),
                            Ativo = false,
                            CodPonto = 78,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8765),
                            HoraAula = 52.00m,
                            Nome = "DANIELA LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7733d054-9b53-4b99-9fa5-027f5032620a"),
                            Ativo = false,
                            CodPonto = 79,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8769),
                            HoraAula = 52.00m,
                            Nome = "ALAN GOMES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("bc0e9aa9-3dfe-4d05-8e69-8722eac8fe08"),
                            Ativo = false,
                            CodPonto = 80,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8774),
                            HoraAula = 52.00m,
                            Nome = "KASSIO FERNANDO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8249c209-d67e-4439-82c8-a54d1bf4f8b6"),
                            Ativo = false,
                            CodPonto = 81,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8779),
                            HoraAula = 52.00m,
                            Nome = "MARYANNE STEPHANE ROCHA G",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f53b9827-9a91-496a-85d5-d511f93cec2a"),
                            Ativo = false,
                            CodPonto = 76,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8784),
                            HoraAula = 52.00m,
                            Nome = "FERNANDO ATROCH",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("67041274-0fdf-43ce-8c7d-6db602670378"),
                            Ativo = false,
                            CodPonto = 82,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8789),
                            HoraAula = 52.00m,
                            Nome = "PEDRO AUGUSTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("eb356426-a9ea-4860-963b-b26f9476acb7"),
                            Ativo = false,
                            CodPonto = 83,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8794),
                            HoraAula = 52.00m,
                            Nome = "ELAINE JULIANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2ff438dd-207c-4d18-9e73-3a3df133a852"),
                            Ativo = false,
                            CodPonto = 84,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8801),
                            HoraAula = 52.00m,
                            Nome = "JOSELINO DANTAS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8e78b276-7a28-42f4-b5b0-5712ef786bd4"),
                            Ativo = false,
                            CodPonto = 85,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8807),
                            HoraAula = 52.00m,
                            Nome = "BRNDAO REINALDO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5ef05dc9-2c8c-40b9-8093-3f2ddaafea93"),
                            Ativo = false,
                            CodPonto = 86,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8813),
                            HoraAula = 52.00m,
                            Nome = "MOISES HAMSSES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8fb60c73-00ce-446f-a8b5-276c7e31e0e6"),
                            Ativo = false,
                            CodPonto = 87,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8818),
                            HoraAula = 52.00m,
                            Nome = "DIANA MARROCOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5e0ada3e-e45d-4653-85aa-1bae7ed94ff2"),
                            Ativo = false,
                            CodPonto = 88,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8823),
                            HoraAula = 52.00m,
                            Nome = "JOAO VICTOR",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("677bd6fb-f0db-4bc9-9736-07287e6d0139"),
                            Ativo = false,
                            CodPonto = 89,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8828),
                            HoraAula = 52.00m,
                            Nome = "EDNA MOIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4cd58bc1-e51c-4185-ba86-ada154f87a5c"),
                            Ativo = false,
                            CodPonto = 91,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8832),
                            HoraAula = 52.00m,
                            Nome = "MARCIA BARRETO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("63842210-2055-47ef-a70c-f302ae19268c"),
                            Ativo = false,
                            CodPonto = 94,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8837),
                            HoraAula = 52.00m,
                            Nome = "JESSICA MELO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3fad560a-a7aa-4491-897f-9c0388a960f2"),
                            Ativo = false,
                            CodPonto = 93,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8844),
                            HoraAula = 52.00m,
                            Nome = "TARCIA ALEXANDRE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1e1e6eb0-702c-4933-86ef-c228412fd363"),
                            Ativo = false,
                            CodPonto = 90,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8849),
                            HoraAula = 52.00m,
                            Nome = "WELLIDA AVIZ",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("afcfde8f-c285-457b-84a8-80f8c194cc4e"),
                            Ativo = false,
                            CodPonto = 95,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8853),
                            HoraAula = 52.00m,
                            Nome = "FERNANDO AMOURY",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d2dc555e-d0e8-4154-b4d7-151ba7f8d57d"),
                            Ativo = false,
                            CodPonto = 77,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8858),
                            HoraAula = 52.00m,
                            Nome = "ALLAN WERBERTT",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("35f964b9-e422-4c9e-a166-260ec0b0bc64"),
                            Ativo = false,
                            CodPonto = 96,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8862),
                            HoraAula = 52.00m,
                            Nome = "THAISE MORGANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a8f05b31-84dd-4465-812a-1b0383046993"),
                            Ativo = false,
                            CodPonto = 97,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8867),
                            HoraAula = 52.00m,
                            Nome = "CRISLANE SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a32b76b1-9035-46b2-9d9a-fe4db729e119"),
                            Ativo = false,
                            CodPonto = 98,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8872),
                            HoraAula = 52.00m,
                            Nome = "YARA OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d3b4f040-e09d-4b78-a2e2-788b9503c274"),
                            Ativo = false,
                            CodPonto = 99,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8876),
                            HoraAula = 52.00m,
                            Nome = "LUCIANO LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("adee6549-804a-4820-939e-e1b7eeb0565d"),
                            Ativo = false,
                            CodPonto = 100,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8884),
                            HoraAula = 52.00m,
                            Nome = "FRANCYANNE CASTRO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d95175bb-8518-4be5-9aa4-9fd45f60ed11"),
                            Ativo = false,
                            CodPonto = 101,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8889),
                            HoraAula = 52.00m,
                            Nome = "KESIA MARTINS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4d1f33e9-ef0a-4be1-b55b-77c1b7eb371c"),
                            Ativo = false,
                            CodPonto = 102,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8893),
                            HoraAula = 52.00m,
                            Nome = "MAIZA NONATO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("51d11f6f-2fc8-4a76-816e-abe40ea22e40"),
                            Ativo = false,
                            CodPonto = 103,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8898),
                            HoraAula = 52.00m,
                            Nome = "ANDERSON MACIEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("cb2f0839-b9b5-4fb3-8f6b-9afc5d88b7f8"),
                            Ativo = false,
                            CodPonto = 104,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8903),
                            HoraAula = 52.00m,
                            Nome = "RODRIGO CESAR",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6b08d06d-f270-4b0c-b34e-19dac6e09cb2"),
                            Ativo = false,
                            CodPonto = 105,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8907),
                            HoraAula = 52.00m,
                            Nome = "JOSE DE ARIMATEIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("41cf0b64-4769-4f2d-9025-b2e4eb0f0c39"),
                            Ativo = false,
                            CodPonto = 106,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8912),
                            HoraAula = 52.00m,
                            Nome = "HENRIQUE NOLETO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d8ce8bf3-44e9-4584-a267-89c4b45485df"),
                            Ativo = false,
                            CodPonto = 107,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8916),
                            HoraAula = 52.00m,
                            Nome = "ISABELA MARTINS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b772a677-c8ab-4b02-b326-55bb221fb107"),
                            Ativo = false,
                            CodPonto = 108,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8924),
                            HoraAula = 52.00m,
                            Nome = "IOLENE VIANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("78239da9-8a51-4f5f-86f1-178ed7021bd7"),
                            Ativo = false,
                            CodPonto = 109,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8929),
                            HoraAula = 52.00m,
                            Nome = "WESLLEY SOARES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d19aa01f-eb5d-4b55-bd22-7ba0f5f434dc"),
                            Ativo = false,
                            CodPonto = 110,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8934),
                            HoraAula = 52.00m,
                            Nome = "DIVINO SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ae2d2e4f-7e9d-4b93-b2eb-cd77fbe72935"),
                            Ativo = false,
                            CodPonto = 111,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8938),
                            HoraAula = 52.00m,
                            Nome = "ALINE LOPES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6974312d-09bb-470b-b97c-9ccd5e5df49b"),
                            Ativo = false,
                            CodPonto = 112,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8943),
                            HoraAula = 52.00m,
                            Nome = "JOSIEL MACIEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("17feb1e5-8b6b-492b-8794-25791bcb3da4"),
                            Ativo = false,
                            CodPonto = 113,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8947),
                            HoraAula = 52.00m,
                            Nome = "TATIANA RODRIGUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d409636d-3c47-4853-8d73-ee0506e9810c"),
                            Ativo = false,
                            CodPonto = 114,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8952),
                            HoraAula = 52.00m,
                            Nome = "IVANA TUTORIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3d4920b8-9a5f-46c3-b052-39aeacc2821d"),
                            Ativo = false,
                            CodPonto = 115,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8956),
                            HoraAula = 52.00m,
                            Nome = "CARLOS EDUARDO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("fe53f049-0dda-4a7d-bc1c-b86b7ae6afc2"),
                            Ativo = false,
                            CodPonto = 116,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(8994),
                            HoraAula = 52.00m,
                            Nome = "CASSIO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6fbf841e-8970-4ce5-88b3-eda8396d0037"),
                            Ativo = false,
                            CodPonto = 117,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9000),
                            HoraAula = 52.00m,
                            Nome = "ELLEN CLEIDE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("579a488b-9984-4ab6-bf00-d736d85636ae"),
                            Ativo = false,
                            CodPonto = 118,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9005),
                            HoraAula = 52.00m,
                            Nome = "MARIA MARLI",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9b549916-e79a-43fa-99d5-0b9643ffbf55"),
                            Ativo = false,
                            CodPonto = 119,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9009),
                            HoraAula = 52.00m,
                            Nome = "MIRIA FERREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("e86cb9c7-85ca-4ef5-9157-d858137296f6"),
                            Ativo = false,
                            CodPonto = 120,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9014),
                            HoraAula = 52.00m,
                            Nome = "VICTOR DE PAULA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("481ac085-27e6-4de6-bf11-067528d033ab"),
                            Ativo = false,
                            CodPonto = 121,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9019),
                            HoraAula = 52.00m,
                            Nome = "ANA TEREZA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d622c959-4a3c-4c15-a7ca-8f7346a8f37d"),
                            Ativo = false,
                            CodPonto = 122,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9023),
                            HoraAula = 52.00m,
                            Nome = "HEYGON TED",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("52261f3e-e18b-4567-a167-29021d890fa7"),
                            Ativo = false,
                            CodPonto = 123,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9028),
                            HoraAula = 52.00m,
                            Nome = "RILDO AMARAL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("19fe23bf-98bf-4c3f-91a1-b35834a0fd12"),
                            Ativo = false,
                            CodPonto = 124,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9035),
                            HoraAula = 52.00m,
                            Nome = "GERLYNNE PESSOA DE CARVALHO SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4cda752e-bba8-49a3-bed3-175ebb7e0be3"),
                            Ativo = false,
                            CodPonto = 125,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9040),
                            HoraAula = 52.00m,
                            Nome = "MATHEUS HENRIQUE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f3e7ef6e-6d07-45f6-8540-f82b1248987f"),
                            Ativo = false,
                            CodPonto = 126,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9044),
                            HoraAula = 52.00m,
                            Nome = "THAMYRES SALOMAO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("491ef176-ae1c-464c-8b12-a8c4cd8dc9a5"),
                            Ativo = false,
                            CodPonto = 127,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9049),
                            HoraAula = 52.00m,
                            Nome = "SAMILLY GURGEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("eaead136-b29b-4cd1-9abd-32ecea8583d3"),
                            Ativo = false,
                            CodPonto = 128,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9054),
                            HoraAula = 52.00m,
                            Nome = "HILLARY SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a80425ae-9c87-4a18-b216-a355360da4b2"),
                            Ativo = false,
                            CodPonto = 129,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9058),
                            HoraAula = 52.00m,
                            Nome = "PALMEIRA JR",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("dd8f1296-cdd7-4682-a58a-8c25084f7139"),
                            Ativo = false,
                            CodPonto = 130,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9063),
                            HoraAula = 52.00m,
                            Nome = "RONIEL MARQUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4feb08b7-efa4-482f-bbdd-95d8ccee3dca"),
                            Ativo = false,
                            CodPonto = 131,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9068),
                            HoraAula = 52.00m,
                            Nome = "ALINE PEREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5f30dcbb-0283-4090-8f2e-40dd357a7b14"),
                            Ativo = false,
                            CodPonto = 132,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9075),
                            HoraAula = 52.00m,
                            Nome = "RAYANE MARTINS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f4cdffa1-d3b4-471b-970f-343a4a0a0bd9"),
                            Ativo = false,
                            CodPonto = 133,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9080),
                            HoraAula = 52.00m,
                            Nome = "LIDIA SOUSA BARROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6a5c280b-3ec4-40db-9c23-4d3e4393d04d"),
                            Ativo = false,
                            CodPonto = 134,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9084),
                            HoraAula = 52.00m,
                            Nome = "ELZA MARIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6ee63c73-aa6d-4ead-b1c8-a7354c62f1c2"),
                            Ativo = false,
                            CodPonto = 135,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9089),
                            HoraAula = 52.00m,
                            Nome = "SELMA OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1e450daa-d71c-4757-bfac-6a7bc751df65"),
                            Ativo = false,
                            CodPonto = 136,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9094),
                            HoraAula = 52.00m,
                            Nome = "CAMILA LETICIA P",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5be8556f-42ae-4591-a57e-9d7dd0c66cf3"),
                            Ativo = false,
                            CodPonto = 137,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9098),
                            HoraAula = 52.00m,
                            Nome = "THIAGO MESQUITA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("474ed4e9-415e-4d80-81a2-b94367ca5e66"),
                            Ativo = false,
                            CodPonto = 138,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9104),
                            HoraAula = 52.00m,
                            Nome = "IRLAINE SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ae71c842-7b20-4b4c-9652-de5df14c2b99"),
                            Ativo = false,
                            CodPonto = 139,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9109),
                            HoraAula = 52.00m,
                            Nome = "CARLOS ALBERTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4dc6567f-bee9-4500-b4f0-095ed6486e1d"),
                            Ativo = false,
                            CodPonto = 140,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9117),
                            HoraAula = 52.00m,
                            Nome = "ERIVELTON DOS SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("16a9da81-cb5f-4348-94e0-2ad6795bc1a3"),
                            Ativo = false,
                            CodPonto = 141,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9121),
                            HoraAula = 52.00m,
                            Nome = "ERICK LEAO FERRAZ",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("335ae038-cf85-40b8-8f12-51931979df0a"),
                            Ativo = false,
                            CodPonto = 142,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9126),
                            HoraAula = 52.00m,
                            Nome = "LARISSA CARDOSO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b375c925-6b38-4933-9c64-bd032c2c4b35"),
                            Ativo = false,
                            CodPonto = 143,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9132),
                            HoraAula = 52.00m,
                            Nome = "SERGIO DE JESUS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c62aacb1-da32-4368-86e5-393081eb31c0"),
                            Ativo = false,
                            CodPonto = 144,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9137),
                            HoraAula = 52.00m,
                            Nome = "FLAVIANA DE OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3f3ec614-6090-4607-a340-cbc7906dab8c"),
                            Ativo = false,
                            CodPonto = 145,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9142),
                            HoraAula = 52.00m,
                            Nome = "AMANDA GOULART",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("769e07f0-b8a6-4d0b-a69b-8b2f12ed3383"),
                            Ativo = false,
                            CodPonto = 146,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9147),
                            HoraAula = 52.00m,
                            Nome = "ADAO DE PAULA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ff89dabd-9a49-4633-b1de-279c4b512c4b"),
                            Ativo = false,
                            CodPonto = 147,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9152),
                            HoraAula = 52.00m,
                            Nome = "SIMONE SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("28f79feb-e148-4fa6-bb97-c1c1d37ad1ad"),
                            Ativo = false,
                            CodPonto = 148,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9160),
                            HoraAula = 52.00m,
                            Nome = "LUCIMARA FONSECA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ca63ee31-d211-4473-887a-f62b847f7aca"),
                            Ativo = false,
                            CodPonto = 149,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9165),
                            HoraAula = 52.00m,
                            Nome = "CARMEM NATANNA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3f6ba8cf-1543-419f-ad60-d13cb06b408e"),
                            Ativo = false,
                            CodPonto = 150,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9169),
                            HoraAula = 52.00m,
                            Nome = "RAIRONE LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c7e75968-808f-4093-8ffa-b3d8136a35c9"),
                            Ativo = false,
                            CodPonto = 151,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9174),
                            HoraAula = 52.00m,
                            Nome = "RODRIGO DRELIN",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a24d198f-efc7-4194-8a02-3ec8c178127e"),
                            Ativo = false,
                            CodPonto = 152,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9178),
                            HoraAula = 52.00m,
                            Nome = "KALIMY DE SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("fa637094-8776-415a-b811-4aa37751ba16"),
                            Ativo = false,
                            CodPonto = 153,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9183),
                            HoraAula = 52.00m,
                            Nome = "CYMARA FRANCO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6200f935-8974-4817-9221-23346894e9bc"),
                            Ativo = false,
                            CodPonto = 154,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9187),
                            HoraAula = 52.00m,
                            Nome = "SCARLETT MILHOMEM",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a3e7e575-a9f0-4d84-bb65-47f1c7585a17"),
                            Ativo = false,
                            CodPonto = 155,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9192),
                            HoraAula = 52.00m,
                            Nome = "KIANE SANTANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b2c7cdae-cfcf-4f7f-ad7d-c52bf85d512e"),
                            Ativo = false,
                            CodPonto = 156,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9199),
                            HoraAula = 52.00m,
                            Nome = "EDUARDO MENDES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6d5d2b11-e247-43fe-9ec1-1d9da215cb05"),
                            Ativo = false,
                            CodPonto = 157,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9234),
                            HoraAula = 52.00m,
                            Nome = "JUCILENE SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("28e4a120-0485-4a85-bf81-a8ffd2cf46ef"),
                            Ativo = false,
                            CodPonto = 158,
                            Contratacao = new DateTime(2021, 10, 20, 21, 38, 30, 386, DateTimeKind.Local).AddTicks(9239),
                            HoraAula = 52.00m,
                            Nome = "ALMIR DALMOLIN",
                            Numero = 0,
                            Salario = 5000.00m
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnderecoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Email");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3aa1abb7-be38-4a5d-952e-5e2d72663d31"),
                            EnderecoEmail = "edivaldomachado@gmailcom",
                            Nome = "Edivaldo"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFeriado")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFeriado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feriado");
                });

            modelBuilder.Entity("BlazorServer.Data.RegistroPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AM_ENT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AM_SAI")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NOI_ENT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NOI_SAI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PM_ENT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PM_SAI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("RegistroPontos");
                });

            modelBuilder.Entity("BlazorServer.Data.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e765e564-7df0-417c-a171-1ccef5c761a8"),
                            Bairro = "Bairro da Paz",
                            CNPJ = "123123123/1234-12",
                            Cidade = "Parauapebas",
                            Endereco = "Rua Sol Poente",
                            Nome = "Parauapebas",
                            Numero = 152,
                            RazaoSocial = "EDIVALDO MACHADO BARBALHO"
                        },
                        new
                        {
                            Id = new Guid("a542f40c-8e41-4b0d-9db2-61b881433d26"),
                            Bairro = "Centro",
                            CNPJ = "123123123/1234-12",
                            Cidade = "Eldorado dos Carajás",
                            Endereco = "Rua Sol Poente",
                            Nome = "Eldorado dos Carajas",
                            Numero = 152,
                            RazaoSocial = "EDIVALDO MACHADO BARBALHO"
                        },
                        new
                        {
                            Id = new Guid("07c2dffd-568b-4dfd-a65c-ec39246708bc"),
                            Bairro = "Centro",
                            CNPJ = "123123123/1234-12",
                            Cidade = "Canaa dos Carajas",
                            Endereco = "Rua Sol Poente",
                            Nome = "Canaa dos CArajas",
                            Numero = 152,
                            RazaoSocial = "EDIVALDO MACHADO BARBALHO"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Colaborador", b =>
                {
                    b.HasOne("BlazorServer.Data.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CargoId");

                    b.HasOne("BlazorServer.Data.Unidade", "Unidade")
                        .WithMany("Colaboradores")
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Cargo");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BlazorServer.Data.RegistroPonto", b =>
                {
                    b.HasOne("BlazorServer.Data.Colaborador", "Colaborador")
                        .WithMany("Registros")
                        .HasForeignKey("ColaboradorId");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("BlazorServer.Data.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("BlazorServer.Data.Colaborador", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("BlazorServer.Data.Unidade", b =>
                {
                    b.Navigation("Colaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
