// <auto-generated />
using System;
using BlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211015195135_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorServer.Data.Arquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caminho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Arquivo");
                });

            modelBuilder.Entity("BlazorServer.Data.Cargo", b =>
                {
                    b.Property<Guid>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCargo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargoId");

                    b.ToTable("Cargo");

                    b.HasData(
                        new
                        {
                            CargoId = new Guid("7b0550b3-d76b-4fe7-8585-b19ce620ccab"),
                            NomeCargo = "Tutor"
                        },
                        new
                        {
                            CargoId = new Guid("0f1ae776-0094-4c85-9a6e-80ac99d6e808"),
                            NomeCargo = "Secretaria"
                        },
                        new
                        {
                            CargoId = new Guid("a0847cc0-ad29-4d52-abfa-3ff6e4178045"),
                            NomeCargo = "Comercial"
                        },
                        new
                        {
                            CargoId = new Guid("a3f6551a-e3e0-42fd-b3fc-c62af5f386e3"),
                            NomeCargo = "Coordenador"
                        },
                        new
                        {
                            CargoId = new Guid("94834a19-9021-494e-af0b-086900298969"),
                            NomeCargo = "Professor"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodPonto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Contratacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Demissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HoraAula")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UnidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Colaboradors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("598f1b88-0b46-4bea-ac60-858502539d05"),
                            Ativo = false,
                            CodPonto = 39,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 144, DateTimeKind.Local).AddTicks(41),
                            HoraAula = 52.00m,
                            Nome = "ALEXSANDRA KETHY DE FRANÇA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4acece27-deef-435b-a760-057f4b9f5f6b"),
                            Ativo = false,
                            CodPonto = 22,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4553),
                            HoraAula = 52.00m,
                            Nome = "ALVARO RICK P. VIEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("687dc936-6ce2-4e23-b534-ac7d83a11eaf"),
                            Ativo = false,
                            CodPonto = 50,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4604),
                            HoraAula = 52.00m,
                            Nome = "AMADEU JUNIOR FERREIRA DE LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("47657922-aa83-400c-81b4-c2ca55b0f9cd"),
                            Ativo = false,
                            CodPonto = 46,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4613),
                            HoraAula = 52.00m,
                            Nome = "ANA ALICE DA MOTA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("467fb42b-a7d8-4c97-aaf2-fd8fee3c41dd"),
                            Ativo = false,
                            CodPonto = 35,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4629),
                            HoraAula = 52.00m,
                            Nome = "ANDERSON CRISTIANO SALES SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("96fec84b-9771-49fa-8883-ba1eae351585"),
                            Ativo = false,
                            CodPonto = 5,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4634),
                            HoraAula = 52.00m,
                            Nome = "ANDRÉ DA CONCEIÇÃO SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8c847145-4d46-4baf-b374-663e1598daf4"),
                            Ativo = false,
                            CodPonto = 37,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4640),
                            HoraAula = 52.00m,
                            Nome = "ANDREA REGINA J. B. RODRIGUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7f4de793-ea69-4b1b-b0ae-9c942034d732"),
                            Ativo = false,
                            CodPonto = 42,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4645),
                            HoraAula = 52.00m,
                            Nome = "ANTONIA IVANA COSTA SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7b9f1c88-f8fc-4d4b-879e-2483b027e963"),
                            Ativo = false,
                            CodPonto = 26,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4651),
                            HoraAula = 52.00m,
                            Nome = "CACIELY VALERIO GOMES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("91df3a4d-bc4b-4ebf-a12e-17a045673c21"),
                            Ativo = false,
                            CodPonto = 25,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4656),
                            HoraAula = 52.00m,
                            Nome = "CLEUDILENE DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1de028d1-f15d-47a3-bb8c-53d0f1f13ced"),
                            Ativo = false,
                            CodPonto = 44,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4661),
                            HoraAula = 52.00m,
                            Nome = "CRISTIANE SOARES COSTA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("931a52ae-85d3-4337-858f-7583ac8384e2"),
                            Ativo = false,
                            CodPonto = 40,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4666),
                            HoraAula = 52.00m,
                            Nome = "DANIEL DE ARAUJO MOTA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("cd48aa6c-aed8-48f2-9455-1b8241a04edf"),
                            Ativo = false,
                            CodPonto = 41,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4675),
                            HoraAula = 52.00m,
                            Nome = "DAYARA BORGES LUCENA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("466e82b7-f3a0-4dd6-a6af-875a0e543f7b"),
                            Ativo = false,
                            CodPonto = 36,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4680),
                            HoraAula = 52.00m,
                            Nome = "DENILZA  ALVES PINTO DUARTE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("53782617-315d-4beb-858c-dba6d92a3c4d"),
                            Ativo = false,
                            CodPonto = 28,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4685),
                            HoraAula = 52.00m,
                            Nome = "DEREK DILERVANDO DE O. PANTOJA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("dfe99170-dd2d-43f6-8ee1-55b8709e5e0c"),
                            Ativo = false,
                            CodPonto = 19,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4691),
                            HoraAula = 52.00m,
                            Nome = "DHONAYARA DA SILVA DE CAMPOS AMORIM",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6874a8fd-7aaa-4037-8a85-cf5afba50d56"),
                            Ativo = false,
                            CodPonto = 2,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4696),
                            HoraAula = 52.00m,
                            Nome = "EDI",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("887b401f-11ba-4af2-ac19-3cf82673f406"),
                            Ativo = false,
                            CodPonto = 45,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4701),
                            HoraAula = 52.00m,
                            Nome = "ELAINE DE JESUS REZENDE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a0732dc9-dc59-4a06-adda-522679d8a0b2"),
                            Ativo = false,
                            CodPonto = 48,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4706),
                            HoraAula = 52.00m,
                            Nome = "ERCILIO DE CASTRO  BARBOZA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5774af66-ba17-4da5-8af2-d4d6d1222d48"),
                            Ativo = false,
                            CodPonto = 29,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4712),
                            HoraAula = 52.00m,
                            Nome = "FERNANDO CABRAL DA FONSECA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9d664384-6da6-4d70-a82c-c61be7bc1a26"),
                            Ativo = false,
                            CodPonto = 24,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4796),
                            HoraAula = 52.00m,
                            Nome = "FRANCINOLIA R A L C",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f193eaa0-091a-4e7b-8997-2db1ce9acab1"),
                            Ativo = false,
                            CodPonto = 9,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4803),
                            HoraAula = 52.00m,
                            Nome = "GLICIANE ESTEPHANE JACOME DE SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("954caf10-40a5-454a-b438-32cc1b9e10e1"),
                            Ativo = false,
                            CodPonto = 31,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4808),
                            HoraAula = 52.00m,
                            Nome = "HUDLER LEITE DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("358a92cc-028e-41af-8332-72e5c52b7db9"),
                            Ativo = false,
                            CodPonto = 33,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4814),
                            HoraAula = 52.00m,
                            Nome = "IRISMAR SILVA CIRINO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("214e015e-3ede-41fe-97a9-e22925e00756"),
                            Ativo = false,
                            CodPonto = 34,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4819),
                            HoraAula = 52.00m,
                            Nome = "JAKELLYNE ALVES BRANDÃO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9436cdcc-7a93-4571-9303-a0cd1f255954"),
                            Ativo = false,
                            CodPonto = 10,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4824),
                            HoraAula = 52.00m,
                            Nome = "JHYEIVSON WALLINTER SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("303904be-089b-407c-999b-c8be4383a406"),
                            Ativo = false,
                            CodPonto = 43,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4829),
                            HoraAula = 52.00m,
                            Nome = "JORDANIA DE MACEDO MENDONÇA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f3f8e193-7b2e-484a-91c8-538e1b0a7390"),
                            Ativo = false,
                            CodPonto = 11,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4834),
                            HoraAula = 52.00m,
                            Nome = "JORGE CLESIO SILVA E SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2d9b2bd8-e918-45a4-be4d-263189037a56"),
                            Ativo = false,
                            CodPonto = 12,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4842),
                            HoraAula = 52.00m,
                            Nome = "JORGE FERNANDO CASTRO SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b37fa7a5-95e4-41cf-8ed9-2a7e61d68f32"),
                            Ativo = false,
                            CodPonto = 51,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4848),
                            HoraAula = 52.00m,
                            Nome = "JUCIENE IONARIA DE S. GABRIEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("50b6a36f-99a3-4a76-965a-7c996644aa98"),
                            Ativo = false,
                            CodPonto = 55,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4853),
                            HoraAula = 52.00m,
                            Nome = "LEILSON RODRIGUES DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("030712fb-8807-47eb-9dfa-87c031c7ab45"),
                            Ativo = false,
                            CodPonto = 13,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4858),
                            HoraAula = 52.00m,
                            Nome = "LORENA MATOS SILVA PRADO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1e8ad998-2d1f-4caf-ae2a-1b1c15bd1c85"),
                            Ativo = false,
                            CodPonto = 30,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4863),
                            HoraAula = 52.00m,
                            Nome = "LUANA MARTINS ROCHA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b478cb73-3f1e-4383-a4a8-6b72499d327e"),
                            Ativo = false,
                            CodPonto = 53,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4867),
                            HoraAula = 52.00m,
                            Nome = "MARIANA LEAL OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f53a397e-1b4a-4924-8da8-046555376855"),
                            Ativo = false,
                            CodPonto = 14,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4872),
                            HoraAula = 52.00m,
                            Nome = "MAYARA DE OLIVEIRA PEREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3571f896-497d-4f54-ba6f-956c383238c6"),
                            Ativo = false,
                            CodPonto = 27,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4877),
                            HoraAula = 52.00m,
                            Nome = "MONICA HELLE DE LIMA ROSA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("298aaf31-5873-44cc-a8b9-5d1cefb24880"),
                            Ativo = false,
                            CodPonto = 3,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4884),
                            HoraAula = 52.00m,
                            Nome = "NATANAEL SOUA BARROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7f1e2e0c-172f-47d9-ae2b-1dd9a79b4ce1"),
                            Ativo = false,
                            CodPonto = 54,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4889),
                            HoraAula = 52.00m,
                            Nome = "NATHALIA DA SILVA MARQUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d18d414b-0520-4c0a-99e7-22fb8e0f46e3"),
                            Ativo = false,
                            CodPonto = 38,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4893),
                            HoraAula = 52.00m,
                            Nome = "NILCELIA DE LIMA ROCHA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("68821a39-ba61-45d6-830b-f374f86a9495"),
                            Ativo = false,
                            CodPonto = 23,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4899),
                            HoraAula = 52.00m,
                            Nome = "RAIANE OCAES OLIVEIRA DE SOUZA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("a349a734-a8cc-4199-9fd5-764ac9549cfa"),
                            Ativo = false,
                            CodPonto = 20,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4903),
                            HoraAula = 52.00m,
                            Nome = "RAILENE CONCEIÇÃO DE CARVALHO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7c331f34-ab22-4fa9-8e69-f45f75346f09"),
                            Ativo = false,
                            CodPonto = 15,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4908),
                            HoraAula = 52.00m,
                            Nome = "RAQUEL BRITO DOS SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("fb3978f3-25fd-46f0-a608-c99964b416d1"),
                            Ativo = false,
                            CodPonto = 32,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4913),
                            HoraAula = 52.00m,
                            Nome = "ROSILENE CONCEIÇÃO DE CARVALHO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("68723160-5470-41f6-a7b4-82cda790509c"),
                            Ativo = false,
                            CodPonto = 16,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4917),
                            HoraAula = 52.00m,
                            Nome = "SAMARA DE OLIVEIRA MOREIRA CABRAL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("268af7b2-79b8-47dc-8a6d-be5bde083195"),
                            Ativo = false,
                            CodPonto = 47,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4924),
                            HoraAula = 52.00m,
                            Nome = "SILVIO VIANA DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("217f2c12-0f40-48e6-b02e-ce40b39f1de9"),
                            Ativo = false,
                            CodPonto = 4,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4929),
                            HoraAula = 52.00m,
                            Nome = "SIRLEI VANDA ANDRADE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2274c9d8-e0e4-4754-bd06-3a6930bf7e9c"),
                            Ativo = false,
                            CodPonto = 56,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4934),
                            HoraAula = 52.00m,
                            Nome = "SUANY ISAIAS DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4c9a5bea-b8ac-458d-a3f4-da19a33e4236"),
                            Ativo = false,
                            CodPonto = 17,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4939),
                            HoraAula = 52.00m,
                            Nome = "TOMAZ B. NERY S. CAMPOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ba54784b-52aa-4610-afa1-99fbe86b50f3"),
                            Ativo = false,
                            CodPonto = 49,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4943),
                            HoraAula = 52.00m,
                            Nome = "VANESSA MOURA DE ALMEIDA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3cac08da-b6db-46f6-b573-b27902d4ffe4"),
                            Ativo = false,
                            CodPonto = 18,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4948),
                            HoraAula = 52.00m,
                            Nome = "WALDEMIR DE SOUZA REIS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d8cf5c09-bc5f-4aa0-8089-0a57bb847067"),
                            Ativo = false,
                            CodPonto = 21,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4952),
                            HoraAula = 52.00m,
                            Nome = "WALISON RICARDO GOES DA PASCOA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("328a07eb-b21a-48fc-891d-e2b2568302a8"),
                            Ativo = false,
                            CodPonto = 52,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4957),
                            HoraAula = 52.00m,
                            Nome = "WARLY BEZERRA DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("0f2b5d29-51ee-4508-85e9-502381c46192"),
                            Ativo = false,
                            CodPonto = 57,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4965),
                            HoraAula = 52.00m,
                            Nome = "RENATA CAMILY SIRQUEIRA PALHETA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("597b4013-cc24-4020-8644-f40ffba07a0b"),
                            Ativo = false,
                            CodPonto = 58,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4969),
                            HoraAula = 52.00m,
                            Nome = "YURI DO CARMO MOREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("94d4559f-224b-4a37-b60a-fdfaad2138a5"),
                            Ativo = false,
                            CodPonto = 59,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4974),
                            HoraAula = 52.00m,
                            Nome = "VALDEMAR JUSTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("94312824-cf78-42fe-976f-344fdf536e9c"),
                            Ativo = false,
                            CodPonto = 60,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4979),
                            HoraAula = 52.00m,
                            Nome = "EDSON DA SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d9281b9b-58b9-4fe3-8fc4-eb274793bec3"),
                            Ativo = false,
                            CodPonto = 61,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4983),
                            HoraAula = 52.00m,
                            Nome = "BRUNO MORAES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8c2b71ef-b097-45a5-8137-c86a19d42938"),
                            Ativo = false,
                            CodPonto = 6,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4988),
                            HoraAula = 52.00m,
                            Nome = "CIBELLE DA SILVA CARVALHO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("e634cb92-cf90-4298-86e4-f44c1ef8bf30"),
                            Ativo = false,
                            CodPonto = 62,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4993),
                            HoraAula = 52.00m,
                            Nome = "THALYTA RODRIGUES BARBOSA GIL		 ",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d22eb047-2879-470d-99dd-ad7a2ab72d70"),
                            Ativo = false,
                            CodPonto = 64,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(4997),
                            HoraAula = 52.00m,
                            Nome = "DHELEN SILVA ALMEIDA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("65d92418-6f53-463b-8edc-45c1383e7096"),
                            Ativo = false,
                            CodPonto = 63,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5004),
                            HoraAula = 52.00m,
                            Nome = "DEUZIMAR LIMA DOS SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6e8cc103-65f9-4062-b848-c97d4adcc867"),
                            Ativo = false,
                            CodPonto = 7,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5040),
                            HoraAula = 52.00m,
                            Nome = "DAYARA NOLETO ALVES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("e8887d61-abec-4ae0-9cf1-f84bad681e53"),
                            Ativo = false,
                            CodPonto = 65,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5045),
                            HoraAula = 52.00m,
                            Nome = "LORENE SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2ff8eef0-d5b5-4433-badd-c411748b3e2a"),
                            Ativo = false,
                            CodPonto = 66,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5050),
                            HoraAula = 52.00m,
                            Nome = "JOSE ROBERTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1387ceab-f16b-42b0-b21d-5d4c94e9e307"),
                            Ativo = false,
                            CodPonto = 67,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5055),
                            HoraAula = 52.00m,
                            Nome = "GABRIEL DE ARAUJO VEIGA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9f3e36d6-d1dd-4fa9-a8d6-b06ec80729c8"),
                            Ativo = false,
                            CodPonto = 68,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5060),
                            HoraAula = 52.00m,
                            Nome = "MIREIA SOZA BARROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ec71bdb0-2656-4330-95a4-b6014419c7c6"),
                            Ativo = false,
                            CodPonto = 69,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5065),
                            HoraAula = 52.00m,
                            Nome = "MARINA LINS DE SOUZA AMADO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6581d353-5bb7-4c89-b2c7-5bbeeda311a5"),
                            Ativo = false,
                            CodPonto = 70,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5069),
                            HoraAula = 52.00m,
                            Nome = "ALVESLENE LEMS C DAMACENO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("052d2080-09b8-44f6-9004-cdd8f03a5ab5"),
                            Ativo = false,
                            CodPonto = 71,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5077),
                            HoraAula = 52.00m,
                            Nome = "APINAGES PIRES CARDOSO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("fd4bb908-9c34-4f8a-abc3-c40c6a588998"),
                            Ativo = false,
                            CodPonto = 72,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5081),
                            HoraAula = 52.00m,
                            Nome = "LUCAS MEDEIROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8ad37739-8b0d-4b84-8a0d-3f321a78ee2c"),
                            Ativo = false,
                            CodPonto = 73,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5086),
                            HoraAula = 52.00m,
                            Nome = "ELIANE MORAES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("dec8a62d-ec98-4540-8d03-21c546a6818d"),
                            Ativo = false,
                            CodPonto = 74,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5091),
                            HoraAula = 52.00m,
                            Nome = "DANIELLE LIMA SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3aedc916-4b1a-4f98-acda-343a1dccfd81"),
                            Ativo = false,
                            CodPonto = 75,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5096),
                            HoraAula = 52.00m,
                            Nome = "TASSIO VINICIUS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c9f33ec5-0876-4670-811c-af7fa83bd5e3"),
                            Ativo = false,
                            CodPonto = 78,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5101),
                            HoraAula = 52.00m,
                            Nome = "DANIELA LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1043533f-4271-4f4e-92e6-10e183e51e5c"),
                            Ativo = false,
                            CodPonto = 79,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5106),
                            HoraAula = 52.00m,
                            Nome = "ALAN GOMES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("84acfd06-c7cc-4ad2-a29c-0bbe84356463"),
                            Ativo = false,
                            CodPonto = 80,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5112),
                            HoraAula = 52.00m,
                            Nome = "KASSIO FERNANDO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4f4e931b-de12-4f29-8076-a1f4d89122f5"),
                            Ativo = false,
                            CodPonto = 81,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5119),
                            HoraAula = 52.00m,
                            Nome = "MARYANNE STEPHANE ROCHA G",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("48ba4bb7-864e-41f8-b4c6-59c342e073ed"),
                            Ativo = false,
                            CodPonto = 76,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5124),
                            HoraAula = 52.00m,
                            Nome = "FERNANDO ATROCH",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8ce97934-47c5-41f7-9cf8-d143e81c71fd"),
                            Ativo = false,
                            CodPonto = 82,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5129),
                            HoraAula = 52.00m,
                            Nome = "PEDRO AUGUSTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("37b647c6-18e2-41f8-a348-4ebf33e70eb0"),
                            Ativo = false,
                            CodPonto = 83,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5135),
                            HoraAula = 52.00m,
                            Nome = "ELAINE JULIANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d52de0e5-fe61-4cae-a173-8e8367cfa063"),
                            Ativo = false,
                            CodPonto = 84,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5140),
                            HoraAula = 52.00m,
                            Nome = "JOSELINO DANTAS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("187c260e-e666-45f8-af53-da3fd39c0f88"),
                            Ativo = false,
                            CodPonto = 85,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5145),
                            HoraAula = 52.00m,
                            Nome = "BRNDAO REINALDO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7cc6575d-5fb6-41a1-9898-bb9923e0b1f4"),
                            Ativo = false,
                            CodPonto = 86,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5150),
                            HoraAula = 52.00m,
                            Nome = "MOISES HAMSSES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("93ccd682-52a5-4252-9957-7c0fc0b78674"),
                            Ativo = false,
                            CodPonto = 87,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5154),
                            HoraAula = 52.00m,
                            Nome = "DIANA MARROCOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("25e834fd-1de1-4821-ba93-3ba5ec166f5e"),
                            Ativo = false,
                            CodPonto = 88,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5161),
                            HoraAula = 52.00m,
                            Nome = "JOAO VICTOR",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("6d455397-f9a5-4279-a0bb-edbff64d0a37"),
                            Ativo = false,
                            CodPonto = 89,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5166),
                            HoraAula = 52.00m,
                            Nome = "EDNA MOIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("759ef78c-daa0-4ca8-84a4-90e6a4675757"),
                            Ativo = false,
                            CodPonto = 91,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5171),
                            HoraAula = 52.00m,
                            Nome = "MARCIA BARRETO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b07cc473-b7ad-4f00-8f71-3d31a5bd6033"),
                            Ativo = false,
                            CodPonto = 94,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5176),
                            HoraAula = 52.00m,
                            Nome = "JESSICA MELO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4418c1e4-c3af-42d3-bd42-b63acdca8571"),
                            Ativo = false,
                            CodPonto = 93,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5181),
                            HoraAula = 52.00m,
                            Nome = "TARCIA ALEXANDRE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2c825bb1-d8ee-4b2f-942a-533f63e721ec"),
                            Ativo = false,
                            CodPonto = 90,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5185),
                            HoraAula = 52.00m,
                            Nome = "WELLIDA AVIZ",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("60ceb10f-5aa3-4f79-847a-f2a746bb11e6"),
                            Ativo = false,
                            CodPonto = 95,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5190),
                            HoraAula = 52.00m,
                            Nome = "FERNANDO AMOURY",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("bd5e1902-6be9-438a-8bce-d86e941d4056"),
                            Ativo = false,
                            CodPonto = 77,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5194),
                            HoraAula = 52.00m,
                            Nome = "ALLAN WERBERTT",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("49a44040-944d-4f97-8748-0a622cf45cf9"),
                            Ativo = false,
                            CodPonto = 96,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5202),
                            HoraAula = 52.00m,
                            Nome = "THAISE MORGANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("8b5e1ed6-37d6-42ea-a639-a38e3d8ba02e"),
                            Ativo = false,
                            CodPonto = 97,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5206),
                            HoraAula = 52.00m,
                            Nome = "CRISLANE SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("e111f4a1-9589-48f2-a167-84069370ab50"),
                            Ativo = false,
                            CodPonto = 98,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5211),
                            HoraAula = 52.00m,
                            Nome = "YARA OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d46c0718-8aeb-400d-a7f7-642acf86c503"),
                            Ativo = false,
                            CodPonto = 99,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5217),
                            HoraAula = 52.00m,
                            Nome = "LUCIANO LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ae51755c-b7a2-4d63-89a2-268d4e756065"),
                            Ativo = false,
                            CodPonto = 100,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5223),
                            HoraAula = 52.00m,
                            Nome = "FRANCYANNE CASTRO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("96096f68-65ce-446c-bcfb-429572036d6c"),
                            Ativo = false,
                            CodPonto = 101,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5227),
                            HoraAula = 52.00m,
                            Nome = "KESIA MARTINS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("956dcfbd-72fb-4033-b73a-61b5aaf1840d"),
                            Ativo = false,
                            CodPonto = 102,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5232),
                            HoraAula = 52.00m,
                            Nome = "MAIZA NONATO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("24227a79-7f7c-43c2-82cb-9699ccb9c877"),
                            Ativo = false,
                            CodPonto = 103,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5237),
                            HoraAula = 52.00m,
                            Nome = "ANDERSON MACIEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9ec35927-0f4c-4f09-a877-ce838381a87e"),
                            Ativo = false,
                            CodPonto = 104,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5244),
                            HoraAula = 52.00m,
                            Nome = "RODRIGO CESAR",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5fe79161-acf4-43f9-b89e-4b3142ca7089"),
                            Ativo = false,
                            CodPonto = 105,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5279),
                            HoraAula = 52.00m,
                            Nome = "JOSE DE ARIMATEIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3174ac99-4073-4fa8-ba3e-db38cf4f15b8"),
                            Ativo = false,
                            CodPonto = 106,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5284),
                            HoraAula = 52.00m,
                            Nome = "HENRIQUE NOLETO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("452bdd15-aeea-430e-8cd2-219c3bd2377f"),
                            Ativo = false,
                            CodPonto = 107,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5289),
                            HoraAula = 52.00m,
                            Nome = "ISABELA MARTINS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("bea7445c-571d-401b-a415-96958e229b9d"),
                            Ativo = false,
                            CodPonto = 108,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5294),
                            HoraAula = 52.00m,
                            Nome = "IOLENE VIANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("63d811d4-66e7-446e-9adb-b12957c33ca4"),
                            Ativo = false,
                            CodPonto = 109,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5298),
                            HoraAula = 52.00m,
                            Nome = "WESLLEY SOARES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("ac14ec82-3f6e-4bbd-a112-8457fab258ca"),
                            Ativo = false,
                            CodPonto = 110,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5304),
                            HoraAula = 52.00m,
                            Nome = "DIVINO SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2015cca8-eda0-45eb-a362-5458aebec528"),
                            Ativo = false,
                            CodPonto = 111,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5308),
                            HoraAula = 52.00m,
                            Nome = "ALINE LOPES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("5043bc1f-7028-4f8b-a9f0-16146e5cac21"),
                            Ativo = false,
                            CodPonto = 112,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5315),
                            HoraAula = 52.00m,
                            Nome = "JOSIEL MACIEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("03f39b64-c2df-4da1-b51e-d7cd0303d971"),
                            Ativo = false,
                            CodPonto = 113,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5320),
                            HoraAula = 52.00m,
                            Nome = "TATIANA RODRIGUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d57d4b43-a5d9-401c-bfba-0d1d3d5e131b"),
                            Ativo = false,
                            CodPonto = 114,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5325),
                            HoraAula = 52.00m,
                            Nome = "IVANA TUTORIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("0e50ee7c-08e4-48c3-89a6-8b4ecf8e7200"),
                            Ativo = false,
                            CodPonto = 115,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5330),
                            HoraAula = 52.00m,
                            Nome = "CARLOS EDUARDO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d7031db3-70b4-4b74-ba2a-82e1740dfb22"),
                            Ativo = false,
                            CodPonto = 116,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5334),
                            HoraAula = 52.00m,
                            Nome = "CASSIO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c79c24dc-78fc-4354-82da-e7f6a2f0447a"),
                            Ativo = false,
                            CodPonto = 117,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5339),
                            HoraAula = 52.00m,
                            Nome = "ELLEN CLEIDE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9ec2371b-9f56-4640-a7ed-ed90d4d18dc7"),
                            Ativo = false,
                            CodPonto = 118,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5344),
                            HoraAula = 52.00m,
                            Nome = "MARIA MARLI",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("61fc6da3-0d17-48f6-8770-137fcb117ecd"),
                            Ativo = false,
                            CodPonto = 119,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5348),
                            HoraAula = 52.00m,
                            Nome = "MIRIA FERREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("0032bb0a-6110-43e0-919f-dcbf9cec1447"),
                            Ativo = false,
                            CodPonto = 120,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5355),
                            HoraAula = 52.00m,
                            Nome = "VICTOR DE PAULA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("228ac6ca-036c-4ee4-a92b-bf5c01f02952"),
                            Ativo = false,
                            CodPonto = 121,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5361),
                            HoraAula = 52.00m,
                            Nome = "ANA TEREZA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("7d75d2f4-77f6-42a5-8124-a439553b7f12"),
                            Ativo = false,
                            CodPonto = 122,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5365),
                            HoraAula = 52.00m,
                            Nome = "HEYGON TED",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4d74b9a2-7368-4a4e-bc9d-3addb6ffb03e"),
                            Ativo = false,
                            CodPonto = 123,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5370),
                            HoraAula = 52.00m,
                            Nome = "RILDO AMARAL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f9776ef5-9afe-4eab-8f2d-31df604607b8"),
                            Ativo = false,
                            CodPonto = 124,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5375),
                            HoraAula = 52.00m,
                            Nome = "GERLYNNE PESSOA DE CARVALHO SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9dc1989c-9773-46ab-ac6c-873d862013c8"),
                            Ativo = false,
                            CodPonto = 125,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5379),
                            HoraAula = 52.00m,
                            Nome = "MATHEUS HENRIQUE",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2d556766-97df-46fe-ab57-6ee55e22319f"),
                            Ativo = false,
                            CodPonto = 126,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5384),
                            HoraAula = 52.00m,
                            Nome = "THAMYRES SALOMAO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("005aed0b-914e-41c7-baa0-bcff79ede8d1"),
                            Ativo = false,
                            CodPonto = 127,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5388),
                            HoraAula = 52.00m,
                            Nome = "SAMILLY GURGEL",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c1d2a46c-3905-48f1-981c-89d3b84bc698"),
                            Ativo = false,
                            CodPonto = 128,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5395),
                            HoraAula = 52.00m,
                            Nome = "HILLARY SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b2f09482-2617-4ce8-8124-c02f54d2bb01"),
                            Ativo = false,
                            CodPonto = 129,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5400),
                            HoraAula = 52.00m,
                            Nome = "PALMEIRA JR",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c1b42e3e-781f-4e30-a1e6-b8697ba58bbc"),
                            Ativo = false,
                            CodPonto = 130,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5405),
                            HoraAula = 52.00m,
                            Nome = "RONIEL MARQUES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("1b502316-2954-4840-ad98-d7d1e39e9e5a"),
                            Ativo = false,
                            CodPonto = 131,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5409),
                            HoraAula = 52.00m,
                            Nome = "ALINE PEREIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d04612aa-dc89-4e93-bde9-3ed98ea004a4"),
                            Ativo = false,
                            CodPonto = 132,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5414),
                            HoraAula = 52.00m,
                            Nome = "RAYANE MARTINS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("eb11772f-2ef7-4b46-8284-bdb36128491f"),
                            Ativo = false,
                            CodPonto = 133,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5419),
                            HoraAula = 52.00m,
                            Nome = "LIDIA SOUSA BARROS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("cb381a71-27f4-47df-80fe-b018dc2e0cb3"),
                            Ativo = false,
                            CodPonto = 134,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5424),
                            HoraAula = 52.00m,
                            Nome = "ELZA MARIA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("b141df9b-96d0-45f8-8ce8-ba39d0f9c89e"),
                            Ativo = false,
                            CodPonto = 135,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5429),
                            HoraAula = 52.00m,
                            Nome = "SELMA OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c6ac368e-6c51-4497-b60a-c022159c8ebe"),
                            Ativo = false,
                            CodPonto = 136,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5437),
                            HoraAula = 52.00m,
                            Nome = "CAMILA LETICIA P",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2fb62d67-5f38-4890-90f0-43b92aa845fb"),
                            Ativo = false,
                            CodPonto = 137,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5442),
                            HoraAula = 52.00m,
                            Nome = "THIAGO MESQUITA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9df54a97-fbf1-44e6-b4f6-1844decbdedf"),
                            Ativo = false,
                            CodPonto = 138,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5447),
                            HoraAula = 52.00m,
                            Nome = "IRLAINE SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("483f3173-67a4-48d7-aa25-8ea84e448431"),
                            Ativo = false,
                            CodPonto = 139,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5453),
                            HoraAula = 52.00m,
                            Nome = "CARLOS ALBERTO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("0ba970bf-61e3-416e-9ef6-d858fd389a47"),
                            Ativo = false,
                            CodPonto = 140,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5459),
                            HoraAula = 52.00m,
                            Nome = "ERIVELTON DOS SANTOS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("691b8ac6-c0c2-4ce3-87fa-b50f51bcba2b"),
                            Ativo = false,
                            CodPonto = 141,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5464),
                            HoraAula = 52.00m,
                            Nome = "ERICK LEAO FERRAZ",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("882177ab-8f21-43d7-8275-2ff7facafd3b"),
                            Ativo = false,
                            CodPonto = 142,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5471),
                            HoraAula = 52.00m,
                            Nome = "LARISSA CARDOSO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("e9e27857-4a41-4ea6-8e6a-a3cac2ae1fa9"),
                            Ativo = false,
                            CodPonto = 143,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5476),
                            HoraAula = 52.00m,
                            Nome = "SERGIO DE JESUS",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("2ccdf7be-3e6e-4da3-8bc8-64c5d2d8fd43"),
                            Ativo = false,
                            CodPonto = 144,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5483),
                            HoraAula = 52.00m,
                            Nome = "FLAVIANA DE OLIVEIRA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("544c90cb-bb5b-496a-ab23-53c0a5a1ac79"),
                            Ativo = false,
                            CodPonto = 145,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5488),
                            HoraAula = 52.00m,
                            Nome = "AMANDA GOULART",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c02675a9-d686-40cc-b707-cb39d95b891c"),
                            Ativo = false,
                            CodPonto = 146,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5526),
                            HoraAula = 52.00m,
                            Nome = "ADAO DE PAULA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("407ac359-c13e-44c9-845d-0ea92a47f950"),
                            Ativo = false,
                            CodPonto = 147,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5532),
                            HoraAula = 52.00m,
                            Nome = "SIMONE SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("f81ea21e-4336-4dcd-96b0-60fe27e1cff5"),
                            Ativo = false,
                            CodPonto = 148,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5537),
                            HoraAula = 52.00m,
                            Nome = "LUCIMARA FONSECA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("4cd69df7-cc87-47dd-b0a6-2688d9eb2610"),
                            Ativo = false,
                            CodPonto = 149,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5541),
                            HoraAula = 52.00m,
                            Nome = "CARMEM NATANNA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("c91faccd-abaa-4bf7-9660-1dfaa7f0b39b"),
                            Ativo = false,
                            CodPonto = 150,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5550),
                            HoraAula = 52.00m,
                            Nome = "RAIRONE LIMA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("d2f0ce15-12bc-4f49-854b-a6a27f7e71de"),
                            Ativo = false,
                            CodPonto = 151,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5555),
                            HoraAula = 52.00m,
                            Nome = "RODRIGO DRELIN",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("9771390f-7d6e-4c70-a435-233613ce8e68"),
                            Ativo = false,
                            CodPonto = 152,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5562),
                            HoraAula = 52.00m,
                            Nome = "KALIMY DE SOUSA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("3b9fb735-5a43-4730-a142-45fe5484144c"),
                            Ativo = false,
                            CodPonto = 153,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5567),
                            HoraAula = 52.00m,
                            Nome = "CYMARA FRANCO",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("30f4bfa9-87c4-4aae-8704-d9cbb353b263"),
                            Ativo = false,
                            CodPonto = 154,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5572),
                            HoraAula = 52.00m,
                            Nome = "SCARLETT MILHOMEM",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("351d561b-bf8e-4b4b-ad80-0d8bfa0febb6"),
                            Ativo = false,
                            CodPonto = 155,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5576),
                            HoraAula = 52.00m,
                            Nome = "KIANE SANTANA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("261008c7-62e4-4fab-b0e5-8b5bd0177ce9"),
                            Ativo = false,
                            CodPonto = 156,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5581),
                            HoraAula = 52.00m,
                            Nome = "EDUARDO MENDES",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("0229e1fe-0e23-4b07-9bdd-0738b2740e7d"),
                            Ativo = false,
                            CodPonto = 157,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5586),
                            HoraAula = 52.00m,
                            Nome = "JUCILENE SILVA",
                            Numero = 0,
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("43dce4db-3e3a-41e4-be43-d80d4e0b13ca"),
                            Ativo = false,
                            CodPonto = 158,
                            Contratacao = new DateTime(2021, 10, 15, 16, 51, 35, 145, DateTimeKind.Local).AddTicks(5590),
                            HoraAula = 52.00m,
                            Nome = "ALMIR DALMOLIN",
                            Numero = 0,
                            Salario = 5000.00m
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnderecoEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Email");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83c58185-8745-40d8-adb2-0ff484130aba"),
                            EnderecoEmail = "edivaldomachado@gmailcom",
                            Nome = "Edivaldo"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFeriado")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeFeriado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feriado");
                });

            modelBuilder.Entity("BlazorServer.Data.RegistroPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AM_ENT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AM_SAI")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NOI_ENT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NOI_SAI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PM_ENT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PM_SAI")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("RegistroPontos");
                });

            modelBuilder.Entity("BlazorServer.Data.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8ad5b4b-4b37-4a7f-b46b-e0eccacaaf53"),
                            Bairro = "Bairro da Paz",
                            CNPJ = "123123123/1234-12",
                            Cidade = "Parauapebas",
                            Endereco = "Rua Sol Poente",
                            Nome = "Parauapebas",
                            Numero = 152,
                            RazaoSocial = "EDIVALDO MACHADO BARBALHO"
                        },
                        new
                        {
                            Id = new Guid("1b468c55-97bd-4e72-b604-6e08aa5aeb4c"),
                            Bairro = "Centro",
                            CNPJ = "123123123/1234-12",
                            Cidade = "Eldorado dos Carajás",
                            Endereco = "Rua Sol Poente",
                            Nome = "Eldorado dos Carajas",
                            Numero = 152,
                            RazaoSocial = "EDIVALDO MACHADO BARBALHO"
                        },
                        new
                        {
                            Id = new Guid("220b46cb-d2d1-4657-96f9-b58b81bf80a4"),
                            Bairro = "Centro",
                            CNPJ = "123123123/1234-12",
                            Cidade = "Canaa dos Carajas",
                            Endereco = "Rua Sol Poente",
                            Nome = "Canaa dos CArajas",
                            Numero = 152,
                            RazaoSocial = "EDIVALDO MACHADO BARBALHO"
                        });
                });

            modelBuilder.Entity("BlazorServer.Data.Colaborador", b =>
                {
                    b.HasOne("BlazorServer.Data.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CargoId");

                    b.HasOne("BlazorServer.Data.Unidade", "Unidade")
                        .WithMany("Colaboradores")
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Cargo");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("BlazorServer.Data.RegistroPonto", b =>
                {
                    b.HasOne("BlazorServer.Data.Colaborador", "Colaborador")
                        .WithMany("Registros")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("BlazorServer.Data.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("BlazorServer.Data.Colaborador", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("BlazorServer.Data.Unidade", b =>
                {
                    b.Navigation("Colaboradores");
                });
#pragma warning restore 612, 618
        }
    }
}
